### DISCUSSION TITLE
Using ccache instead of this pod

### DISCUSSION THREAD

**Discussion by mikehardy** [invertase/firestore-ios-sdk-frameworks#82] [General]
Hello! This is a discussion to introduce the idea of [ccache ](https://ccache.dev/)and help people integrate it in place of using this pod

Basic knowledge to start:

1) Compiling FirebaseFirestore from scratch takes a long time, especially in CI environments that have limited CPU and no Xcode cache available
1) This pod has the sole purpose of speeding up the build time for the FirebaseFirestore cocoapod - a "build time optimization"
1) This pod, and ccache are both "build time optimizations". They have the same purpose, so ccache may be considered an alternative solution to this pod
1) This pod is "built" by extracting the FirebaseFirestore xcframework from the firebase-ios-sdk "prebuilt" zip file (so the compilation work is already done!) and re-packaging it as a cocoapod
1) Sometimes the way firebase-ios-sdk is structured, and the way it interdepends on itself, causes this repackaging to be invalid - *it is a fragile solution*
1) ccache, as a lower-level compilation cache will work every time, it is less fragile than this pod. But that is only *once configured correctly* it needs correct setup and you need to preserve the cache across CI runs for it to work

Okay, so with the basic knowledge out of the way. If you want to try ccache, here's what you need:

## install ccache 

- local machine: `brew install ccache` should be sufficient
- in CI you might like https://github.com/hendrikmuhs/ccache-action

Test: at this point if you run `which ccache`, it should point to the ccache install and `ccache --version` or `ccache -s` should work.

## link ccache to compiler names

ccache works by *transparently pretending to be xcodebuild's binaries*. So when you call "ld" or "cc", you get ccache first - where it has an opportunity to supply a previously-compiled object. It will then delegate to the underlying xcodebuild tools if that doesn't work, cache the object, then return it.

This is done by making symbolic links in a location in your PATH to the ccache binary. If we assume `/usr/local/bin` is in your PATH, then this should work:

```bash
ln -s $(which ccache) /usr/local/bin/gcc
ln -s $(which ccache) /usr/local/bin/g++
ln -s $(which ccache) /usr/local/bin/cc
ln -s $(which ccache) /usr/local/bin/c++
ln -s $(which ccache) /usr/local/bin/clang
ln -s $(which ccache) /usr/local/bin/clang++
```

In github CI, the ccache-action will do this for you if you use it.

If you used `brew` to install `ccache`, then as @grundid mentions below, there are already symbolic links in a directory ready for you - you just need to prepend `(brew --prefix)/opt/ccache/libexec` to your PATH

Test: At this point if you `which ld` it should point to your symbolic link (for example, `/usr/local/bin/ld`). Success! But, if you run a build, and then run `ccache -s` to look at cache statistics you should see that ccache has 0 hits and 0 misses though - nothing is using it yet.

## Instruct Xcode to use the symbolic links

Xcode, by default, uses "fully-specified paths" to it's tools (clang, clang++ etc) meaning that your new symbolic links that use ccache are not used.

To get Xcode to use ccache first instead of it's own tools, you use a Podfile `post_install` hook that tells Xcode to use *relative* (not fully-specified) names for it's compiler and linker. Now for people building your app that have ccache installed and in their PATH, Xcode will use ccache. For people that do not have ccache installed, the build will still work, just without any compilation speedup.

The modification should look like this:

```ruby
  post_install do |installer|
    react_native_post_install(installer)

    # ...possibly other post_install items here

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Using the un-qualified names means you can swap in different implementations, for example ccache
        config.build_settings["CC"] = "clang"
        config.build_settings["LD"] = "clang"
        config.build_settings["CXX"] = "clang++"
        config.build_settings["LDPLUSPLUS"] = "clang++"
      end
    end

   // ... other stuff perhaps
  
  end
```

You will need to run `pod install` after making this change, as post_install only happens during a pod installation run.

It is also possible to use environment variables defined on the same command line that runs the build, instructing Xcode to use non-fully-specified names for clang etc, which should then resolve to your ccache symbolic links assuming your PATH is configured correctly as verified by the `which` tests above. Here is [an example](https://github.com/invertase/react-native-firebase/blob/605a0df8171c451513125629355027bda2ea5e5d/tests/package.json#L63) using environment variables.

Test: at this point if you run a build, then run `ccache -s` you should see lots of calls to ccache, but there should be 0 hits, and all misses.

If you see 0 hits *and* 0 misses, you need to figure out why ccache is not even called - re-examine your ccache installation + link + PATH steps, and your Xcode build configuration to make sure ccache is where you think it is, the build tool names are in your PATH first, and Xcode is configured to use non-fully-qualified names.

## Configure ccache for iOS builds

ccache by default does not cache objects built the way react-native and Flutter call the compiler, so you have to toggle a few things to make ccache accept that you want to cache the objects.

If you turn on ccache debugging or run `ccache -s` to see statistics, you will note that even with ccache installed, in your PATH, and Xcode using relative paths, ccache is only registering misses.

The specific ccache configuration that should work for these iOS builds is:

```bash
export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
export CCACHE_FILECLONE=true
export CCACHE_DEPEND=true
export CCACHE_INODECACHE=true
```

You may set these in Github Actions workflows in the same step that does the compile or you may set them in your local shell environment.

Alternatively you may wish to configure them in `~/.ccache/ccache.conf` like so:

```
sloppiness = clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
file_clone = true
depend_mode = true
inode_cache = true
```

Test: if you run `ccache -p` it should show these new values for the various things we configure, and if you run a build then run `ccache -s` you should see misses the first run and hits the second run. Congratulations! ccache is now able to optimize your builds.

## Preserve the cache

This is primarily for users in CI.

The first build in any environment with ccache will always be "cold", and not give you any performance benefit as the cache is empty.

The only way to have a "warm" build that is fast and uses a populated cache is to make sure you use the same cache directory between runs.

In CI environments where you have a different virtual machine every time, you need to make use of your CI provider's specific caching mechanism to save the `~/.ccache` after the compile and restore it before the compile between runs.

In Github Workflows, the ccache-action handles this for you, but you will need to handle it yourself in other environments, using whatever caching facilities they provide

## Example

Here is an example using ccache for firebase iOS builds in Github Actions:

- ccache install via action so it is installed and in PATH with symbolic links, and cache restored and has a cache big enough to hold firebase (1.5G): https://github.com/invertase/react-native-firebase/blob/f8b7794db23185c8a934a3e3623e996ce282c1f7/.github/workflows/tests_e2e_ios.yml#L83-L88
- Telling Xcode to use ccache using environment variables, instead of a Podfile snippet - always an option: https://github.com/invertase/react-native-firebase/blob/f8b7794db23185c8a934a3e3623e996ce282c1f7/tests/package.json#L63
- Telling ccache to use flags that work for iOS compilation: https://github.com/invertase/react-native-firebase/blob/f8b7794db23185c8a934a3e3623e996ce282c1f7/.github/workflows/tests_e2e_ios.yml#L147-L153

## Other guides

Others have written of ccache before (in fact, the react-native guide was originally written by me 👋 😆 )

These other guides may be useful:

- [Speeding up your react-native Build phase](https://reactnative.dev/docs/build-speed#use-a-compiler-cache)
- [Optimize Flutter iOS Build using ccache](https://dev.to/leehack/optimize-flutter-ios-build-using-ccache-2oi2)

## Troubleshoot

If you have any difficulties and are unsure why there are misses, carefully check each step above running the "test" for each step to make sure ccache is set up correctly at each step of the way.

If ccache is definitely executing but still 100% misses, you may try turning on ccache logging and examining why or why not ccache decides to cache things. The ccache manual is instructive, as is this article https://interrupt.memfault.com/blog/ccache-debugging

**Comment by mikehardy** [comment]
Please help each other here! If you have gotten this working but only after fixing "this one thing..." posting that one thing may save someone else.

So far these items were mentioned in the issue I pulled this out of:

- people had stale caches and needed to delete `~/Library/Developer/Xcode/DerivedData`, `ios/build` etc and run `pod install` to make it work
- someone had LDFLAGS defined in multiple locations so ccache kept seeing different compile / link arguments and wouldn't used cached versions
- your thing here!

Cheers

**Reply by jmason123** [reply]
As Mike suggested helping each other out, here is where I am at right now. Currently testing on a flutter app. Tested on Android and IOS simulator.

1. Running the command `which gcc` outputs -` /usr/local/bin/gcc`

2. Linking ccache to compiler name;

```
ln -s $(which ccache) /usr/local/bin/gcc
ln -s $(which ccache) /usr/local/bin/g++
ln -s $(which ccache) /usr/local/bin/cc
ln -s $(which ccache) /usr/local/bin/c++
ln -s $(which ccache) /usr/local/bin/clang
ln -s $(which ccache) /usr/local/bin/clang++
```

Confirming they exist.

```
ln: /usr/local/bin/gcc: File exists
ln: /usr/local/bin/g++: File exists
ln: /usr/local/bin/cc: File exists
ln: /usr/local/bin/c++: File exists
ln: /usr/local/bin/clang: File exists
ln: /usr/local/bin/clang++: File exists
```

3.  Podfile curently:


```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Start of the permission_handler configuration
    target.build_configurations.each do |config|

    # Using the un-qualified names means you can swap in different implementations, for example ccache
      config.build_settings["CC"] = "clang"
      config.build_settings["LD"] = "clang"
      config.build_settings["CXX"] = "clang++"
      config.build_settings["LDPLUSPLUS"] = "clang++"
      end
  end
end
```


4. Exports appear to show up as (environment). `ccache -p` outputs

```
(default) absolute_paths_in_stderr = false
(default) base_dir = 
(default) cache_dir = /Users/jmason/Library/Caches/ccache
(default) compiler = 
(default) compiler_check = mtime
(default) compiler_type = auto
(default) compression = true
(default) compression_level = 0
(default) cpp_extension = 
(default) debug = false
(default) debug_dir = 
(environment) depend_mode = true
(default) direct_mode = true
(default) disable = false
(default) extra_files_to_hash = 
(environment) file_clone = true
(default) hard_link = false
(default) hash_dir = true
(default) ignore_headers_in_manifest = 
(default) ignore_options = 
(environment) inode_cache = true
(default) keep_comments_cpp = false
(default) log_file = 
(default) max_files = 0
(default) max_size = 5.0 GiB
(default) msvc_dep_prefix = Note: including file:
(default) namespace = 
(default) path = 
(default) pch_external_checksum = false
(default) prefix_command = 
(default) prefix_command_cpp = 
(default) read_only = false
(default) read_only_direct = false
(default) recache = false
(default) remote_only = false
(default) remote_storage = 
(default) reshare = false
(default) run_second_cpp = true
(environment) sloppiness = clang_index_store, file_stat_matches, include_file_ctime, include_file_mtime, ivfsoverlay, modules, pch_defines, system_headers, time_macros
(default) stats = true
(default) stats_log = 
(default) temporary_dir = /Users/jmason/Library/Caches/ccache/tmp
(default) umask = 
```

After running the app on IOS simulator and Android simulator twice, ccache -s outputs

```
Cacheable calls:     8542 / 36272 (23.55%)
  Hits:              3302 /  8542 (38.66%)
    Direct:          3302 /  3302 (100.0%)
    Preprocessed:       0 /  3302 ( 0.00%)
  Misses:            5240 /  8542 (61.34%)
Uncacheable calls:  27730 / 36272 (76.45%)
Local storage:
  Cache size (GiB):   1.4 /   5.0 (28.58%)
  Hits:              3302 /  8542 (38.66%)
  Misses:            5240 /  8542 (61.34%)

```
Currently my .zshrc file looks like

```
export PATH="/Users/jmason/documents/repos/libraries/flutter/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$PATH":"$HOME/.pub-cache/bin"


export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
export CCACHE_FILECLONE=true
export CCACHE_DEPEND=true
export CCACHE_INODECACHE=true
```
@mikehardy Thank you the extensive guide, the best so far. What are your thoughts on my hit/miss numbers?

**Reply by mikehardy** [reply]
Those look about right for 2 to 3 runs. If you zero stats (ccache -z I think? -h for help...) then rebuild should be 100% or close enough. This looks like you've nailed it though. Assuming so, *all* you're xcode compilation will be fast now. Not just firestore!

**Reply by jmason123** [reply]
@mikehardy Oh I see, the 'cacheable calls' was the total of me trying yesterday and failing haha. After zeroing the stats with `ccache -z` here are my numbers after running on IOS simulator 3 times. 

```
Cacheable calls:    4250 / 4250 (100.0%)
  Hits:             3719 / 4250 (87.51%)
    Direct:         3719 / 3719 (100.0%)
    Preprocessed:      0 / 3719 ( 0.00%)
  Misses:            531 / 4250 (12.49%)
Local storage:
  Cache size (GiB):  2.5 /  5.0 (50.29%)
  Hits:             3719 / 4250 (87.51%)
  Misses:            531 / 4250 (12.49%)
```

My average first build time yesterday without the `invertase/firestore-ios-sdk-frameworks`was 20 minutes (LOL). Consistently, I am getting 100 seconds now. Thanks Mike

**Reply by LeonardoRosaa** [reply]
@jmason123 how are you doing with the GitHub Actions?

**Comment by hnvn** [comment]
Thanks for your sharing, I am using Codemagic for my project, I already tried to setup my CI with `ccache` but it seems something wrong, the build process still takes around 23 minutes, (compare to 10 minutes with pre-compiled framework solution). Here's my CI script:

```
ios-dev-workflow:
    name: iOS Workflow - Deploy Dev Build to Firebase Distribution
    # instance_type: mac_mini
    max_build_duration: 60
      ....
      flutter: 3.16.1
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.ccache
    scripts:
      - name: Install ccache
        script: |
          brew install ccache
          export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
          export CCACHE_FILECLONE=true
          export CCACHE_DEPEND=true
          export CCACHE_INODECACHE=true
          export PATH="/opt/homebrew/opt/ccache/libexec:$PATH" 
      - name: Install Fastlane
        working_directory: ios
        script: |
          gem install fastlane
        #  gem install bundler:2.2.32
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $DEVELOPER_APP_IDENTIFIER --type IOS_APP_ADHOC --create
          app-store-connect fetch-signing-files $NOTIFICATION_SERVICE_EXTENSION_ID --type IOS_APP_ADHOC --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Flutter unit tests
        script: |
          cd . && flutter test
        ignore_failure: true          
      - name: Install Pods
        working_directory: ios
        script: |
          pod install
      - name: Update Gem
        working_directory: ios
        script: |
          bundle install
      - name: Build iOS with Flutter
        script: |
          flutter build ios --release --flavor dev --no-codesign
        # script: |
        #   flutter build ios --release --flavor dev --no-codesign --bundle-sksl-path flutter_ios.sksl.json
      - name: Archive IPA with Fastlane
        working_directory: ios
        script: |
          bundle exec fastlane adhoc_dev export_options:"/Users/builder/export_options.plist"
    publishing:
      scripts:
        - name: Deploy IPA to Firebase Distribution
          script: ....
```
My `Podfile`
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["CC"] = "clang"
      config.build_settings["LD"] = "clang"
      config.build_settings["CXX"] = "clang++"
      config.build_settings["LDPLUSPLUS"] = "clang++"
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
              '$(inherited)',
        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_MICROPHONE=0',
        'PERMISSION_BLUETOOTH=0',
        'AUDIO_SESSION_MICROPHONE=0',
        'PERMISSION_LOCATION=0'
      ]
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
```

**Reply by Origogi** [reply]
@hnvn 

I also experienced the problem of ccahe not hitting when building an ipa using Fastlane in a CI CD environment.

But it works fine on my local PC.

I don't know why ccache doesn't work when building through fastlane in a CICD environment.

However, I found a solution to bypass the above problem.

Modify your workflow as follows

```
flutter build ipa --no-codesign
```

The above command creates xcarchive right before creating the ipa. And ccache becomes a hit, shortening build time.

And in fastlane, we modify it as follows:

```
build_app(
  skip_build_archive: true,
  archive_path: "../build/ios/archive/Runner.xcarchive",
)
```

Due to the added parameter, fastlane only creates the ipa through the pre-created xcarchive.

**Reply by mikehardy** [reply]
My guess is that the environment variables are not propagated step to step. They are not in Github workflows either as far as I know? You might try moving the ccache environment variable settings to be in the same step as the actual build 

I included information above in the troubleshooting that should direct you on how to troubleshoot ccache misses (and how to even know you have them!)

I do not see any calls to `ccache -s` (to check statistics, maybe one call before the build / after the cache restore to make sure the cache restore is working, then one call after the build to check hit/miss).

I do not see any configuration for ccache logging nor an upload of the ccache log as an artifact in your workflow so that you may examine it

As such, you do not appear to have things configured such that you can actually obtain the data and retrieve it so you can help yourself - as such anyone else attempting to help will only be guessing

**Reply by hnvn** [reply]
Thank you guys, let me try with your suggestions and get back with result soon.

**Reply by hnvn** [reply]
I moved the setting of env variables to the build step like this:
```
     - name: Build iOS with Flutter
        script: |
          export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
          export CCACHE_FILECLONE=true
          export CCACHE_DEPEND=true
          export CCACHE_INODECACHE=true
          export PATH="/opt/homebrew/opt/ccache/libexec:$PATH" 
          which ccache
          which ld
          ccache -s
          flutter build ios --release --flavor dev --no-codesign
```
And the result:
```
 /opt/homebrew/bin/ccache
 /usr/bin/ld
 Local storage:
  Cache size (GiB): 0.0 / 5.0 ( 0.00%)
```

**Reply by mikehardy** [reply]
that "which ld" is suspicious, also I think you really want to do a "which clang" - to make sure you have the symbolic links that point a "clang" name in your PATH to /opt/homebrew/bin/ccache

Your Podfile posted above looks like it is doing the right thing with regards to telling Xcode to use relative path names for clang etc, so perhaps it is just the symbolic link creation from compiler/linker names to ccache and making sure those are in the PATH first?

**Reply by Origogi** [reply]
@hnvn 

change build ipa is not ios

> flutter build ipa --no-codesign

**Reply by hnvn** [reply]
@Origogi , I did it, the build time actually decrease (20 min compare to 25 min) but it is not the affect of ccache because the result of `ccache -s` shows that caching is 0%

**Reply by hnvn** [reply]
@mikehardy , I added `which clang` to my script and the result:
```
opt/homebrew/bin/ccache
/usr/bin/ld
/opt/homebrew/opt/ccache/libexec/clang
Local storage:
  Cache size (GiB): 0.0 / 5.0 ( 0.00%)
```
it seems my `PATH` is correct

**Reply by mikehardy** [reply]
@hnvn it seems you are in this part of the document above, note especially enabling logging to inspect why only misses...

----
Troubleshoot
If you have any difficulties and are unsure why there are misses, carefully check each step above running the "test" for each step to make sure ccache is set up correctly at each step of the way.

If ccache is definitely executing but still 100% misses, you may try turning on ccache logging and examining why or why not ccache decides to cache things. The ccache manual is instructive, as is this article https://interrupt.memfault.com/blog/ccache-debugging

**Reply by petrnymsa** [reply]
Hi @hnvn  were you able to solve it? I have same behavior

**Reply by hnvn** [reply]
@petrnymsa , I still get stuck, `ccache` doesn't hit at all. You can try to replace `flutter build ios` by `flutter build ipa`, it actually reduce the build time but it comes from the build command itself, not from `ccache` because I observe the caching size on codemagic management, caching of iOS build is only 137 MB, then it can't be `ccache`. 

**Caution**: if you use Firebase DynamicLink in your project, using `flutter build ipa` solution can cause the DynamicLink stop working, I cannot explain it, I take 2 days to figure out, but I still have no idea about the reason, just roll back to `flutter build ios` and DynamicLink works!

**Reply by Origogi** [reply]
@hnvn 

I discovered why ccache wasn't hitting when building an iOS app through Fastlane in CICD (GitHub Actions).

Initially, I had added these environment variables:

```bash
export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
export CCACHE_FILECLONE=true
export CCACHE_DEPEND=true
export CCACHE_INODECACHE=true
```

However, it seems that Fastlane does not recognize these environment variables, for reasons unknown to me.

To address this, I added the same environment variables directly in Fastlane, and finally, ccache started hitting:

```ruby
ENV["PATH"] = "/usr/lib/ccache:/usr/local/opt/ccache/libexec:#{ENV["PATH"]}"
ENV["CCACHE_SLOPPINESS"] = "clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros"
ENV["CCACHE_FILECLONE"] = "true"
ENV["CCACHE_DEPEND"] = "true"
ENV["CCACHE_INODECACHE"] = "true"

build_app(
  scheme: "dev",
)
```

Please let me know it is working

**Reply by hnvn** [reply]
Thank @Origogi , I will give it a try

**Reply by hnvn** [reply]
@Origogi , what is your configuration for `cache_paths:`

**Reply by Origogi** [reply]
What's mean??

I did not setting ccache path

**Reply by hnvn** [reply]
@Origogi , I mean the cache setting in `codemagic.yaml`:
````
cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.ccache
````

**Reply by Origogi** [reply]
@hnvn 
sorry i did not use codemagic , i use github actions

The caching mechanisms in GitHub Actions and Code Magic are different. In GitHub Actions, i don't set up caching in that way.

However, it's still worth trying as follows:

To make ccache work, you need to modify the PATH and environment variables.

## Environment Variables

```yaml
workflows:
  my-workflow:
    environment:
      vars:
        CCACHE_SLOPPINESS: "clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros"
        CCACHE_FILECLONE: "true"
        CCACHE_DEPEND: "true"
        CCACHE_INODECACHE: "true"
```

and 

## Modifying the PATH

```yaml
workflows:
  my-workflow:
    scripts:
      - name: Update PATH
        script: |
          echo 'export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"' >> $CM_ENV
```
